"""baseline existing schema

Revision ID: 73692c27cbfc
Revises: 
Create Date: 2026-08-22 17:07:50.770267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73692c27cbfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('is_competitive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_cache_app_id'), ['app_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_game_cache_id'), ['id'], unique=False)

    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('is_competitive', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_sessions_id'), ['id'], unique=False)

    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('sleep_start', sa.DateTime(), nullable=True),
    sa.Column('sleep_end', sa.DateTime(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Float(), nullable=True),
    sa.Column('deep_minutes', sa.Integer(), nullable=True),
    sa.Column('light_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_minutes', sa.Integer(), nullable=True),
    sa.Column('awake_minutes', sa.Integer(), nullable=True),
    sa.Column('breathing_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_snapshots_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_health_snapshots_id'), ['id'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('needs_reauth', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_provider'), ['provider'], unique=True)

    op.create_table('sleep_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration_low', sa.Float(), nullable=False),
    sa.Column('duration_high', sa.Float(), nullable=False),
    sa.Column('deep_pct_low', sa.Float(), nullable=False),
    sa.Column('deep_pct_high', sa.Float(), nullable=False),
    sa.Column('rem_pct_low', sa.Float(), nullable=False),
    sa.Column('rem_pct_high', sa.Float(), nullable=False),
    sa.Column('awake_low', sa.Float(), nullable=False),
    sa.Column('awake_high', sa.Float(), nullable=False),
    sa.Column('sample_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_baseline_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_baseline_id'))

    op.drop_table('sleep_baseline')
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_provider'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_id'))

    op.drop_table('oauth_tokens')
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_health_snapshots_date'))

    op.drop_table('health_snapshots')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_game_sessions_game_id'))

    op.drop_table('game_sessions')
    with op.batch_alter_table('game_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_cache_id'))
        batch_op.drop_index(batch_op.f('ix_game_cache_app_id'))

    op.drop_table('game_cache')
    # ### end Alembic commands ###
