"""add synced_at to health_snapshots

Revision ID: 9aebb1523448
Revises: 73692c27cbfc
Create Date: 2026-08-22 17:20:56.415475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aebb1523448'
down_revision: Union[str, Sequence[str], None] = '73692c27cbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_snapshots', schema=None) as batch_op:
        batch_op.drop_column('synced_at')

    # ### end Alembic commands ###
